version: '3'

services:
    ekyc_redis:
        container_name: ekyc_redis
#        image: redis:6.2
        build:
            context: .
        environment:
            - LC_ALL=C.UTF-8
            - LC_COLLATE=C
            - TZ=Asia/Seoul
            - vm.overcommits=1
        volumes:
            - ${PWD}/conf/:/conf/
        restart: always
        ports:
            - "6378:6378"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "1"
        healthcheck:
            test: redis-cli -p 6378 -a "privacy1comtrue2" set a 1 || exit 1 && redis-cli -p 6378 -a "privacy1comtrue2" get a || exit 1
            interval: 3s
            timeout: 3s
            retries: 2
            start_period: 1s
        user: "1001"
        command: sh -c " touch /conf/redis.conf; redis-server /conf/redis.conf"
